version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080" # Adjust the port as needed


  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.client
  #   volumes:
  #     - ./client:/app/client # Mount the client directory
  #   depends_on:
  #     - server # Ensure server container is running before client
