# Use an official Golang runtime as the base image
FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o server .

# Command to run the executable
CMD ["/app/server"]